@extends('layouts.master')

@section('content')
@include('components.search-box')
@include('components.tour-suggest')
@include('components.tour-discount')
@include('components.tour-holiday')
@include('components.cruise')
@include('components.highlight')
@include('components.ads')
@include('components.article')
@include('components.gallery')
@include('components.banner')
@include('components.banner-facebook')
@include('components.partner')
@endsection
